
version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: bizwell-mariadb
      restart: always
      working_dir: /application
      volumes:
        - .:/application
        - ./maria-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=fjHDsf7Qw3G5d4pw
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: bizwell-webserver
      restart: always
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
          - /etc/letsencrypt/live/privatadresser.se/privkey.pem:/etc/ssl/certs/privataddresser-privkey.pem
          - /etc/letsencrypt/live/privatadresser.se/fullchain.pem:/etc/ssl/certs/privataddresser.pem
      ports:
       - "80:80"
       - "443:443"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: bizwell-php-fpm
      restart: always
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    adminer:
      image: adminer
      restart: always
      ports:
        - "8081:8080"

    redis:
      image: redis:alpine
      container_name: bizwell-redis
      restart: always

    queue-worker:
      build: phpdocker/php-fpm
      container_name: bizwell-queue-worker
      restart: always
      working_dir: /application
      volumes:
        - .:/application
      command: ["php", "artisan", "queue:work", "redis", "--sleep=3", "--tries=1", "--queue=bizwell,bizwell_low"]
